# Ilk SSL sertifikasi alinirken kullanilan gecici config
# deploy.sh bu dosyayi otomatik kullanir
server {
    listen 80;
    server_name samplify.tr www.samplify.tr;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 200 'SSL kurulumu devam ediyor...';
        add_header Content-Type text/plain;
    }
}
